### ISSUE TITLE
Manage Recipe Plans

### ISSUE THREAD

**Issue by Daniel-Seifert** [mobileappdevhm20/team-project-team_5#56]
Have a separate view to browse all own or subscribed recipe plans

**Comment by Cavvar** [comment]
The basic view of manage recipe plans is similar to the browse recipe plans. The only difference is from where the mocked data is coming from. As I could see from going through the feature/server branch the related data is coming from the User Entity (CreatedMealPlans, SubscribedMealPlans). My Question is:

Am I supposed to recreate the model with room now and create mocked data for that so that I am able to fill the view?
@Daniel-Seifert

**Comment by Cavvar** [comment]
From the prototype:
![grafik](https://user-images.githubusercontent.com/3383908/83242091-20791e00-a19c-11ea-8048-ef7f555e8dfc.png)
